// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usegbnurqtbbvbmsvohs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZWdibnVycXRiYnZibXN2b2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMzU4MDQsImV4cCI6MjA1MzcxMTgwNH0.CKvsAbBwVSv-ZwjRWG81ZiJJC7aRCiv1rV5kM6TzfhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);